language: cpp
dist: trusty
sudo: true

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - global: CXX_FLAGS="-Wall -Wextra -Werror"

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - valgrind
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - valgrind

install:
  # get cmake-3.10 and dump some debug info
  - mkdir -p ~/cmake
  - curl -ks https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh -o cmake.sh
  - bash cmake.sh --skip-license --prefix="${HOME}/cmake"
  - export PATH=~/cmake/bin:$PATH
  - cmake --version

script:
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0"; fi
  - if [ "$CXX" = "g++" ]    ; then export CXX="g++-7";       fi
  - ${CXX} --version
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DMEMORYCHECK_SUPPRESSIONS_FILE="${TRAVIS_BUILD_DIR}/thorin2/resources/valgrind.supp" ..
  - make -j3 VERBOSE=1
  - ctest -R impala -T memcheck -j3
  - cat ${TRAVIS_BUILD_DIR}/build/Testing/Temporary/MemoryChecker.*.log > out && cat out
  - test ! -s out
